const PDFDocument = require('pdfkit');
const { PassThrough } = require('stream');

/**
 * Generates a clean candidate profile PDF.
 * Returns a Promise that resolves to a Buffer.
 *
 * @param {Object} candidateData
 * @param {string} candidateData.firstName
 * @param {string} candidateData.lastName
 * @param {string} candidateData.email
 * @param {string} candidateData.phone
 * @param {string} candidateData.currentEmployer
 * @param {string} candidateData.currentTitle
 * @param {string} candidateData.linkedinUrl
 * @param {string} candidateData.source
 */
function generateCandidatePdf(candidateData) {
  return new Promise((resolve, reject) => {
    const {
      firstName = '',
      lastName = '',
      email = '',
      phone = '',
      currentEmployer = '',
      currentTitle = '',
      linkedinUrl = '',
      source = '',
    } = candidateData;

    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const passthrough = new PassThrough();
    const chunks = [];

    passthrough.on('data', (chunk) => chunks.push(chunk));
    passthrough.on('end', () => resolve(Buffer.concat(chunks)));
    passthrough.on('error', reject);

    doc.pipe(passthrough);

    const now = new Date();
    const dateStr = now.toLocaleDateString('en-IN', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    // ── Title ──────────────────────────────────────────────────────────────
    doc
      .fontSize(24)
      .font('Helvetica-Bold')
      .fillColor('#1a1a2e')
      .text('Candidate Profile', { align: 'center' });

    doc.moveDown(0.3);

    doc
      .fontSize(10)
      .font('Helvetica')
      .fillColor('#555555')
      .text('Added via Recruiter Extension', { align: 'center' });

    doc
      .fontSize(9)
      .fillColor('#888888')
      .text(dateStr, { align: 'center' });

    doc.moveDown(0.8);

    // ── Divider ────────────────────────────────────────────────────────────
    doc
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor('#cccccc')
      .lineWidth(1)
      .stroke();

    doc.moveDown(1);

    // ── Field helper ───────────────────────────────────────────────────────
    const field = (label, value) => {
      if (!value) return; // skip empty fields
      doc
        .fontSize(9)
        .font('Helvetica-Bold')
        .fillColor('#444444')
        .text(label.toUpperCase(), { continued: false });

      doc
        .fontSize(11)
        .font('Helvetica')
        .fillColor('#1a1a2e')
        .text(value || '—');

      doc.moveDown(0.6);
    };

    field('Full Name', [firstName, lastName].filter(Boolean).join(' '));
    field('Email', email);
    field('Phone', phone);
    field('Current Title', currentTitle);
    field('Current Employer', currentEmployer);
    field('LinkedIn URL', linkedinUrl);
    field('Source Platform', source);

    doc.moveDown(1);

    // ── Divider ────────────────────────────────────────────────────────────
    doc
      .moveTo(50, doc.y)
      .lineTo(545, doc.y)
      .strokeColor('#cccccc')
      .lineWidth(0.5)
      .stroke();

    doc.moveDown(0.8);

    // ── Footer ─────────────────────────────────────────────────────────────
    doc
      .fontSize(8)
      .font('Helvetica')
      .fillColor('#aaaaaa')
      .text(`Generated by Recruiter Extension on ${dateStr}`, { align: 'center' });

    doc.end();
  });
}

module.exports = { generateCandidatePdf };
